version: '3.8'

services:
  app:
    build: .
    container_name: customer_support_agent
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: python src/server.py
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
